services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: altee-core:dev
    container_name: altee-core-dev
    ports:
      - "3000:3000"
    volumes:
      # ソースコードをマウント（ホットリロード対応）
      - .:/app
      # node_modulesは除外（コンテナ内のものを使用）
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - DATABASE_URL=postgresql://postgres:password@db:5432/altee_dev?schema=public
    command: npm run dev
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - altee-network

  db:
    image: postgres:17.4
    container_name: altee-core-db-dev
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=altee_dev
    volumes:
      - altee_dev_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - altee-network

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: altee-core:dev
    container_name: altee-core-prisma-studio
    ports:
      - "5555:5555"
    volumes:
      # ソースコードをマウント（prisma/schema.prismaアクセス用）
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/altee_dev?schema=public
    command: npx prisma studio --hostname 0.0.0.0 --port 5555
    depends_on:
      - db
    networks:
      - altee-network

volumes:
  altee_dev_db_data:

networks:
  altee-network:
    driver: bridge