services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: altee-core:latest
    container_name: altee-core
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - altee-network

networks:
  altee-network:
    driver: bridge